

/////////////////////////////////////////////////////////BB RSI

///////////// RSI
RSIlength = input(6, title="RSI Period Length") 
RSIoverSold = 50
RSIoverBought = 50
price = close
vrsi = rsi(price, RSIlength)

///////////// Bollinger Bands
BBlength = input(200, minval=1, title="Bollinger Period Length")
BBmult = 2 // input(2.0, minval=0.001, maxval=50,title="Bollinger Bands Standard Deviation")
BBbasis = sma(price, BBlength)
BBdev = BBmult * stdev(price, BBlength)
BBupper = BBbasis + BBdev
BBlower = BBbasis - BBdev
source3 = close
buyEntry = crossover(source3, BBlower)
sellEntry = crossunder(source3, BBupper)

plot(BBbasis, color=color.aqua, title="Bollinger Bands SMA Basis Line")
p1 = plot(BBupper, color=color.silver, title="Bollinger Bands Upper Line")
p2 = plot(BBlower, color=color.silver, title="Bollinger Bands Lower Line")
fill(p1, p2)

///////////// Colors
switch1 = input(true, title="Enable Bar Color?")
switch2 = input(true, title="Enable Background Color?")
TrendColor = (RSIoverBought and (price[1] > BBupper and price < BBupper) and BBbasis < BBbasis[1]) ? color.red : (RSIoverSold and (price[1] < BBlower and price > BBlower) and BBbasis > BBbasis[1]) ? color.green : na
barcolor(switch1 ? TrendColor : na)
bgcolor(switch2 ? TrendColor : na, transp=50)

//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_area)
