// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © LuxAlgo

//@version = 4
study(title=" Support and Resistance Levels with Breaks",shorttitle = " Support and Resistance Levels with Breaks [LuxAlgo]", overlay = true ,  max_bars_back=1000)
//
SRtoggleBreaks  = input(true, title = "Show Breaks" )
SRleftBars  = input(15, title = "Left Bars ")
SRrightBars  = input(15, title = "Right Bars")
SRvolumeThresh  = input(20, title = "Volume Threshold")
//
SRhighUsePivot = fixnan(pivothigh(SRleftBars, SRrightBars)[1])
SRlowUsePivot = fixnan(pivotlow(SRleftBars, SRrightBars)[1])
SRr1 = plot(SRhighUsePivot, color=change(SRhighUsePivot) ? na : #FF0000,  linewidth=3, offset=-(SRrightBars+1), title="Resistance")
SRs1 = plot(SRlowUsePivot, color=change(SRlowUsePivot) ? na : #233dee,  linewidth=3, offset=-(SRrightBars+1), title="Support")

//Volume %
SRshort = ema(volume, 5)
SRlong = ema(volume, 10)
SRosc = 100 * (SRshort - SRlong) / SRlong


//For breaks with volume
plotshape(SRtoggleBreaks and crossunder(close,SRlowUsePivot) and not (open - close < high - open) and SRosc > SRvolumeThresh, title = "Break", text = 'B', style = shape.labeldown, location = location.abovebar, color= color.red,textcolor = color.white, transp = 0, size = size.tiny)
plotshape(SRtoggleBreaks and crossover(close,SRhighUsePivot ) and not(open - low > close - open) and SRosc > SRvolumeThresh, title = "Break", text = 'B', style = shape.labelup, location = location.belowbar, color= color.green,textcolor = color.white, transp = 0, size = size.tiny)

//For bull / bear wicks
plotshape(SRtoggleBreaks and crossover(close,SRhighUsePivot ) and open - low > close - open , title = "Break", text = 'Bull Wick', style = shape.labelup, location = location.belowbar, color= color.green,textcolor = color.white, transp = 0, size = size.tiny)
plotshape(SRtoggleBreaks and crossunder(close,SRlowUsePivot) and open - close < high - open , title = "Break", text = 'Bear Wick', style = shape.labeldown, location = location.abovebar, color= color.red,textcolor = color.white, transp = 0, size = size.tiny)


alertcondition(crossunder(close,SRlowUsePivot) and SRosc > SRvolumeThresh , title = "Support Broken" , message = "Support Broken")
alertcondition(crossover(close,SRhighUsePivot) and SRosc > SRvolumeThresh, title = "Resistance Broken" , message = "Resistance Broken")